Reusable Component: OvalButton
Scout-NU/thealleyway-site pull request #115
Opened 2021-04-30 00:04 UTC by isabellberzsenyi

This PR contains code to create the mauve oval button

![image](https://user-images.githubusercontent.com/49954595/116632867-1587ba00-a926-11eb-81e8-1f2d93330fdd.png)

2021-04-30 04:15 UTC, jzhzhang66 requested changes
Everything looks good just that one comment about sizing!

2021-04-30 04:15 UTC, jzhzhang66 commented on components/oval-button/OvalButton.style.js
> +  width: 9em;
Could we change the width to 8em? It's more similar to the hi-fi size 
Also lets add widths for mobile and tablet so they're responsive - maybe something like (this looks good in the browser responsive thing but just double check on your ipad/ phone too) 
mobile: 
    width: 8em;
    height: 3.2em;
tablet: 
    width: 8em;
    height: 3.5em;
desktop: 
    width: 8em;
    height: 3.8em;

I think the main thing is to make sure that on mobile, three of the buttons can fit comfortably in a row like so: 
![image](https://user-images.githubusercontent.com/59738880/116647550-d28b0e00-a948-11eb-899b-572b52852b71.png)

2021-05-01 05:37 UTC, isabellberzsenyi commented
sizing on mobile: 
![Uploading IMG_15E3D127D5AE-1.jpeg…]()

2021-05-01 16:20 UTC, jzhzhang66 approved these changes

2021-05-01 19:48 UTC, jean-zhang approved these changes

2021-05-01 23:56 UTC, merged