Creating the README
Scout-NU/thealleyway-site pull request #2
Opened 2021-02-24 03:30 UTC by isabellberzsenyi

## Story Description

Create and update the README. The README contains information on:
- Starting instruction
- File structure
- Technologies
- Developer contact information

## Notes to Reviewer
File structure and technologies sections will be updated as the code repository works.

2021-02-24 05:42 UTC, jzhzhang66 approved these changes
This looks good to me!

2021-02-24 16:23 UTC, josephmannis requested changes
One other thing to add here would be the file structure and how your code is organized. Also, could you add some more specific instructions on how to deploy the site? 

Other than that looks good to me!

2021-02-24 16:23 UTC, josephmannis commented on README.md
>  npm run dev
Would recommend yarn instead of npm because it can be more reliable for various things, but up to you.

2021-02-24 16:30 UTC, josephmannis commented on README.md
> +PRISMIC_URL="XXXXXXXXXXXXXXX"
Also, can you rename this to something more like PRISMIC_API_KEY if that's what you're storing instead of a URL?

2021-03-03 03:40 UTC, jzhzhang66 reviewed
This looks good - probably a typo but my email is jzhzhang66@gmail.com 
Otherwise, it looks like everything has been changed accordingly to the feedback from Joe.

2021-03-03 20:00 UTC, josephmannis approved these changes
🚀

2021-03-07 21:18 UTC, merged