Refactor: Components into individual folders
Scout-NU/thealleyway-site pull request #63
Opened 2021-03-29 17:25 UTC by jzhzhang66

- Refactored each component into individual folders. This is so we can add in styled components in a separate file under the same folder for organization purposes. 
- Added pageStyles folder. For each page, we can add its styled components file into this folder.

2021-03-29 23:25 UTC, josephmannis approved these changes
This looks good, but I don't see the `pageStyles` folder anywhere!

I also will propose an alternate solution: just put the presentational version of pages under components, something like `components/about-content`. You can then have the `about.js` file just pass in data to the `about-content.js` component. Either works, whatever you and the team prefer.

2021-03-30 22:11 UTC, isabellberzsenyi approved these changes

2021-03-30 22:35 UTC, jean-zhang requested changes

2021-03-30 22:35 UTC, jean-zhang commented on pages/[page].js
> +import React from 'react';
Accidentally copied file?

2021-03-31 22:00 UTC, isabellberzsenyi approved these changes

2021-03-31 22:00 UTC, isabellberzsenyi commented on pages/[page].js
> +import React from 'react';
@jzhzhang66 was this page accidentally added???

2021-03-31 22:48 UTC, merged