Home Page
Scout-NU/thealleyway-site pull request #90
Opened 2021-04-19 10:09 UTC by jean-zhang

### **Note:**
- Sign up confirmation was purposely left out to later incorporate a similar component from the Contact Page
- Animation was added for the arrow, should be straight forward for other related animations
- Animation for bolding required some creativity with shadows because `font-weight` actually cannot be animated. Planning on refactoring into its own component for later reuse

### **High Level Code Overview:**
- `api.js`: updated query to now use `fetchLinks` and decrease the requests to just two, one for the home page and story data, one for just the signatures
- `index.js`, `HomePage.js`: refactored component logic to its own `HomePage` component and various child components
- `TextInputField`: refactored to take in input props

2021-04-19 16:29 UTC, isabellberzsenyi commented on lib/api.js
> +  const { data } = await client.getSingle('home_page', {
beautiful

2021-04-19 16:54 UTC, isabellberzsenyi reviewed
Looks great!
One question: should the chosen featured preview image have some amount of opacity?
![image](https://user-images.githubusercontent.com/49954595/115274042-3f630480-a10e-11eb-98b2-aec6081ca350.png)
![image](https://user-images.githubusercontent.com/49954595/115274070-47bb3f80-a10e-11eb-999f-135814bbe9b1.png)

And a quick comment, I see you're mostly using px instead of ems .. personally I'm ok with that not sure how consistent we want to be with either one or if it matters

---
### Response:
I believe I asked about this in the client meeting. Camaryn prefers the control of editing it herself. Also the images that were chosen were unedited.

2021-04-19 17:04 UTC, jzhzhang66 requested changes
Everything looks great! Just a few comments - the newsletter sign up looks way smaller on the hi-fi. Could you please make it smaller? 
![image](https://user-images.githubusercontent.com/59738880/115275089-5bb37100-a10f-11eb-82e0-ec431e00c379.png)
![image](https://user-images.githubusercontent.com/59738880/115275096-5fdf8e80-a10f-11eb-89bd-a8ec55ea5f6a.png)

---
Response:
Done. Double check you're making comments as part of the review? Otherwise seems like I can't respond in the thread.

2021-04-19 17:05 UTC, jzhzhang66 commented
![image](https://user-images.githubusercontent.com/59738880/115275516-e09e8a80-a10f-11eb-9489-8685851cc502.png)

Something funky w/ the newsletter confirmation popup is happening when I click the submit button

2021-04-19 17:12 UTC, jzhzhang66 commented on style/typography.js
> +  font-size: clamp(1em, 2vw, 1.2em);
I think we should keep the font-size to be 1em - on my desktop, the clamp is making the font-size be 1.2em and it looks too big (and is also a different font size than the featured story description at the top).

2021-04-19 17:13 UTC, jzhzhang66 commented on style/typography.js
> +  font-size: clamp(1em, 2vw, 1.2em);
^^ will also help in reducing the ellipses / newsletter sign up part to be smaller and more similar in size to hi-fi

2021-04-19 17:20 UTC, jzhzhang66 commented
Make the newsletter signup to be responsive (not cut off / there's always padding on the sides) 

![image](https://user-images.githubusercontent.com/59738880/115277163-ed23e280-a111-11eb-9e8f-2cc5b6cf47b0.png)

2021-04-19 17:23 UTC, jzhzhang66 commented
For both of these add line-height: 1.8em to more closely mirror the spacing on the hi-fis
![image](https://user-images.githubusercontent.com/59738880/115277401-3f650380-a112-11eb-904d-eca9c3af96d4.png)
![image](https://user-images.githubusercontent.com/59738880/115277451-4d1a8900-a112-11eb-9068-56e3aa630618.png)

2021-04-19 17:28 UTC, jzhzhang66 commented
Add more top padding 
![image](https://user-images.githubusercontent.com/59738880/115277767-a8e51200-a112-11eb-9904-c398182f7688.png)
![image](https://user-images.githubusercontent.com/59738880/115278140-1abd5b80-a113-11eb-9ab9-567ece54781a.png)

2021-04-19 17:30 UTC, jzhzhang66 commented
The ellipses on mobile should be a lot smaller (notice how close the lines are to the text) 
![image](https://user-images.githubusercontent.com/59738880/115278214-332d7600-a113-11eb-8a06-1f381fc18c23.png)
![image](https://user-images.githubusercontent.com/59738880/115278288-47717300-a113-11eb-9325-757929aaa2bd.png)

2021-04-19 17:30 UTC, jzhzhang66 commented
P.S. I really loved the animation with the arrow:)<3

2021-04-19 17:35 UTC, jzhzhang66 commented
Make sure the popup fits on mobile screen sizes 
![image](https://user-images.githubusercontent.com/59738880/115278992-23626180-a114-11eb-95cb-0928e6c42bea.png)

2021-04-19 17:42 UTC, jzhzhang66 commented
Sorry this is really nitpicky but if you have time could you please round out the top of this shape to somewhere around this line? Right now it looks more pointy than the design 
![image](https://user-images.githubusercontent.com/59738880/115279661-fcf0f600-a114-11eb-9325-b13b63e5cfce.png)
![image](https://user-images.githubusercontent.com/59738880/115279399-b4393d00-a114-11eb-9f32-782d685b7b00.png)

2021-04-19 17:50 UTC, jzhzhang66 reviewed
The code looks really good I think just overall, everything feels too big so just double check with the designs to make sure they're sized similarly!

2021-04-20 17:29 UTC, jzhzhang66 commented on components/homePage/newsletterSignUp/NewsletterSignUp.styles.js
> +  background-color: ${colors.WHITE};
Could you please make the background-color the creme color instead? It's less stark and is what they have on hi-fis i believe

2021-04-21 07:09 UTC, jean-zhang commented
> The code looks really good I think just overall, everything feels too big so just double check with the designs to make sure they're sized similarly!

Bizarre, I used the exact sizes from the HiFis. I'll update.

2021-04-21 15:06 UTC, isabellberzsenyi approved these changes
beautiful

2021-04-21 15:26 UTC, merged